### ISSUE TITLE
Tema Refnet: Bug ao acessar página com os detalhes da estratégia de pesquisa

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/wordpress-themes#187]
Segue mensagem de erro:

`Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/wp-includes/taxonomy.php:2274 Stack trace: #0 /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/wp-includes/taxonomy.php(2274): array_merge() #1 /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/wp-includes/nav-menu-template.php(340): wp_get_object_terms() #2 /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/wp-includes/nav-menu-template.php(196): _wp_menu_item_classes_by_context() #3 /home/repository/wordpress-themes/refnet/header.php(104): wp_nav_menu() #4 /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/wp-includes/template.php(785): require_once('...') #5 /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/wp-includes/template.php(720): load_template() #6 /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/wp-includes/general-template.php(48): locate_template() #7 /home/repository/wordpress-themes/refnet/single-search_strategy.php(42): get_header() #8 /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/wp-includes/template-loader.php(106): include('...') #9 /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/wp-blog-header.php(19): require_once('...') #10 /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/index.php(17): require('...') #11 {main} thrown in /home/apps/bvsalud.org/wp-new-bvsalud/htdocs/wp-includes/taxonomy.php on line 2274`

**Comment by wilsonmoura** [comment]
@marcoslmori ajustes realizados. Favor validar.
